---
  dataSource: "issues"
  prefix: ""
  onlyMilestones: false
  groupBy:
    Hot fixes: ["urgent"]
    Speed Improvements: ["performance"]
    General Enhancements: ["enhancement"]
    Bug Fixes: ["bug"]
    Miscellaneous Changes: ["closed"] 
  changelogFilename: "CHANGELOG.md"
