http.max_content_length: 1gb 
# Better for HDDs (as opposed to SSDs)
index.merge.scheduler.max_thread_count: 1
# How long it takes to make newly indexed documents searchable
# Default is much lower, higher value should help with
# indexing speed
# Leave this at default for tests! Otherwise, the tests will
# fail because newly indexed documents are not available.
#index.refresh_interval: 30s
index.translog.flush_threshold_size: 1gb
# Recommended: ~512MB per shard
indices.memory.index_buffer_size: 2gb
# Events plus ambigue terms = too many bool clauses
index.query.bool.max_clause_count: 4096
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.timeout: 7s
# Activate groovy scripting. We use it for suggestion function queries (sorting).
script.groovy.sandbox.enabled: true
# Allow inline scripts for aggregations, also used for function queries in suggestions
script.engine.groovy.inline.aggs: on
# Deactivate the security manager (new in ES 2.x) to allow ICU plugin and stop filter
# to read files.
# In the future, plugins should be able to do this themselves:
# https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/23
# https://github.com/elastic/elasticsearch/issues/14880
security.manager.enabled: false